name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fruits-api:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fruits-api:latest

  deploy-openshift:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install oc CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify=true

      - name: Set project
        run: oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Delete namespace fruits-ns (if exists)
        run: |
          oc delete namespace fruits-ns || true
          sleep 10
          # Espera a que el namespace se elimine completamente
          while oc get namespace fruits-ns 2>/dev/null; do 
            echo "Esperando que se elimine el namespace..."
            sleep 5
          done

      - name: Apply Deployment
        run: oc apply -f k8s.yaml